// This file is generated by Slice Machine. Update with care!

import BlockLinks from './BlockLinks';
import CallToAction from './CallToAction';
import LogoWithActionButton from './LogoWithActionButton';
import NavigationItem from './NavigationItem';
import ProxyChecker from './ProxyChecker';
import Seo from './Seo';

export { BlockLinks, CallToAction, LogoWithActionButton, NavigationItem, ProxyChecker, Seo };

export const components = {
  block_links: BlockLinks,
  call_to_action: CallToAction,
  logo_with_action_button: LogoWithActionButton,
  navigation_item: NavigationItem,
  proxy_checker: ProxyChecker,
  seo: Seo,
};
