// This file is generated by Slice Machine. Update with care!

import CallToAction from './CallToAction';
import NavigationItem from './NavigationItem';
import ProxyChecker from './ProxyChecker';
import Seo from './Seo';

export { CallToAction, NavigationItem, ProxyChecker, Seo };

export const components = {
  call_to_action: CallToAction,
  navigation_item: NavigationItem,
  proxy_checker: ProxyChecker,
  seo: Seo,
};
